@IsTest
public with sharing class ObjectLayoutForm_Test {

    /**************************************************************
    * Tests the getPageLayoutFieldsWithData function behavior when a layout is not correct.
    *
    * @param void 
    * @throws AssertException
    * @return void
    * @author Adam Albright, @Rehket - github
    * @since 2020-02-21
    */
    @IsTest
    public static void test_invalid_layout_getPageLayoutFieldsWithData(){

    }


    /**************************************************************
    * Tests the getPageLayoutFieldsWithData function behavior when object api name is not correct.
    *
    * @param void 
    * @throws AssertException
    * @return void
    * @author Adam Albright, @Rehket - github
    * @since 2020-02-21
    */
    @IsTest
    public static void test_invalid_object_api_name_getPageLayoutFieldsWithData(){

    }


    /**************************************************************
    * Tests the getPageLayoutFieldsWithData function behavior when object record_id is not correct.
    *
    * @param void 
    * @throws AssertException
    * @return void
    * @author Adam Albright, @Rehket - github
    * @since 2020-02-21
    */
    @IsTest
    public static void test_invalid_record_id_getPageLayoutFieldsWithData(){

    }

    /**************************************************************
    * Tests the test that exception is raised when object field is not a reference.
    *
    * @param field_name 
    * @throws AssertException
    * @return void
    * @author Adam Albright, @Rehket - github
    * @since 2020-02-24
    */


}
